//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photogram.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPost
    {
        public BlogPost()
        {
            this.Visible = false;
            this.Tags = new HashSet<Tag>();
            this.Media = new HashSet<Media>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Lead { get; set; }
        public string Body { get; set; }
        public System.DateTime Modified { get; set; }
        public bool Visible { get; set; }
    
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<Media> Media { get; set; }
        public virtual Media Cover { get; set; }
    }
}
