//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photogram.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public Gallery()
        {
            this.Visible = false;
            this.Title = new HashSet<TextValue>();
            this.Description = new HashSet<TextValue>();
            this.Media = new HashSet<Media>();
        }
    
        public int Id { get; set; }
        public bool Visible { get; set; }
        public GalleryType Type { get; set; }
        public short Year { get; set; }
        public int Position { get; set; }
    
        public virtual ICollection<TextValue> Title { get; set; }
        public virtual ICollection<TextValue> Description { get; set; }
        public virtual ICollection<Media> Media { get; set; }
    }
}
