//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photogram.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.TextValue = new HashSet<TextValue>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
    
        private ICollection<TextValue> TextValue { get; set; }
    }
}
