//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photogram.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public System.DateTime Time { get; set; }
        public LogType Type { get; set; }
    
        public virtual Media Media { get; set; }
        public virtual Project Project { get; set; }
        public virtual TextValue TextValue { get; set; }
        public virtual Setup Setup { get; set; }
        public virtual Language Language { get; set; }
    }
}
