//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photogram.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        public Media()
        {
            this.Title = new HashSet<MediaTitle>();
            this.Description = new HashSet<MediaDescription>();
        }
    
        public int Id { get; set; }
        public string FileName { get; set; }
        public MediaType Type { get; set; }
        public Nullable<int> PositionInProject { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ICollection<MediaTitle> Title { get; set; }
        public virtual ICollection<MediaDescription> Description { get; set; }
    }
}
