//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photogram.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        public Media()
        {
            this.Visible = false;
            this.Gallery = new HashSet<Gallery>();
        }
    
        public int Id { get; set; }
        public string Source { get; set; }
        public bool Visible { get; set; }
        public MediaType Type { get; set; }
    
        public virtual ICollection<Gallery> Gallery { get; set; }
    }
}
