//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photogram.WebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhotogramEntities : DbContext
    {
        public PhotogramEntities()
            : base("name=PhotogramEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Setup> Setup { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<Media> Media { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<Translation> Translation { get; set; }
        public virtual DbSet<ProjectInclude> ProjectInclude { get; set; }
        public virtual DbSet<BlogPost> BlogPost { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
    }
}
