//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photogram.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Visible = false;
            this.Title = new HashSet<ProjectTitle>();
            this.Description = new HashSet<ProjectDescription>();
            this.ProjectInclude = new HashSet<ProjectInclude>();
        }
    
        public int Id { get; set; }
        public bool Visible { get; set; }
        public ProjectType Type { get; set; }
        public short Year { get; set; }
        public int Position { get; set; }
        public string Slug { get; set; }
    
        public virtual ICollection<ProjectTitle> Title { get; set; }
        public virtual ICollection<ProjectDescription> Description { get; set; }
        public virtual ICollection<ProjectInclude> ProjectInclude { get; set; }
    }
}
