//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photogram.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectInclude
    {
        public ProjectInclude()
        {
            this.Cover = false;
        }
    
        public int Id { get; set; }
        public int Position { get; set; }
        public bool Cover { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Media Media { get; set; }
    }
}
