//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photogram.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup
    {
        public Setup()
        {
            this.Published = false;
            this.MainTitle = new HashSet<TextValue>();
            this.Footer = new HashSet<TextValue>();
            this.Log = new HashSet<Log>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public bool Published { get; set; }
    
        public virtual ICollection<TextValue> MainTitle { get; set; }
        public virtual ICollection<TextValue> Footer { get; set; }
        public virtual ICollection<Log> Log { get; set; }
    }
}
