//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photogram.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup
    {
        public Setup()
        {
            this.Published = false;
            this.BlogVisible = false;
            this.MainTitle = new HashSet<SetupMainTitle>();
            this.Footer = new HashSet<SetupFooter>();
            this.AboutLead = new HashSet<SetupAboutLead>();
            this.AboutBody = new HashSet<SetupAboutBody>();
            this.ContactLead = new HashSet<SetupContactLead>();
        }
    
        public int Id { get; set; }
        public bool Published { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string FacebookURL { get; set; }
        public string InstagramURL { get; set; }
        public string GitHubURL { get; set; }
        public string LinkedInURL { get; set; }
        public string BlogName { get; set; }
        public bool BlogVisible { get; set; }
    
        public virtual ICollection<SetupMainTitle> MainTitle { get; set; }
        public virtual ICollection<SetupFooter> Footer { get; set; }
        public virtual ICollection<SetupAboutLead> AboutLead { get; set; }
        public virtual ICollection<SetupAboutBody> AboutBody { get; set; }
        public virtual ICollection<SetupContactLead> ContactLead { get; set; }
        public virtual Media ContactBackground { get; set; }
        public virtual Media AboutBackground { get; set; }
    }
}
