//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photogram.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup
    {
        public Setup()
        {
            this.Published = false;
            this.MainTitle = new HashSet<SetupMainTitle>();
            this.Footer = new HashSet<SetupFooter>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public bool Published { get; set; }
    
        public virtual ICollection<SetupMainTitle> MainTitle { get; set; }
        public virtual ICollection<SetupFooter> Footer { get; set; }
    }
}
