//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photogram.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextValue
    {
        public TextValue()
        {
            this.Log = new HashSet<Log>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
    
        private Setup SetupMainTitle { get; set; }
        private Setup SetupFooter { get; set; }
        private Project ProjectTitle { get; set; }
        private Project ProjectDescription { get; set; }
        public virtual Language Language { get; set; }
        private Media MediaTitle { get; set; }
        private Media MediaDescription { get; set; }
        public virtual ICollection<Log> Log { get; set; }
    }
}
